### ISSUE TITLE
testing the gui

### ISSUE THREAD

**Issue by lcwheeler** [harmslab/pytc#28]
I finally managed to get the GUI to run on my Ubuntu 14.04 machine (thanks to help from Zsailer!). It looks great! Turns out it is very difficult without python 3.5 (newer) and I'm not sure why. However, after installing python 3.6, which allows one to pip install PyQt5, using the GUI went mostly smoothly. I have noticed a couple of issues: 1) choosing a new model requires opening a new session and reloading the data file, which is a little clunky. 2) The program was freezing up for ~30s while fitting a binding polynomial. Otherwise, works smoothly and looks really good.

**Comment by harmsm** [comment]
Fixed. Closing.
