### ISSUE TITLE
Installing pytc on Windows - Printing error for unable to find pyqt5 on install, but gui still able to run

### ISSUE THREAD

**Issue by anloes** [harmslab/pytc#30]
When running setup.py install on Windows, this throws an error - "Could not find suitable distribution for Requirement.parse<ptqt5>". However, there is a folder for PyQt5 which installs with the latest version of Anaconda. The Gui loads and seems to be able to run fine when I execute the gui_main.py script.

**Comment by harmsm** [comment]
Fixed!
