### ISSUE TITLE
Mac GUI issue. 

### ISSUE THREAD

**Issue by Dlangela** [harmslab/pytc#59]
Hello, 

I am interested in trying out pyTC for routine ITC data analysis. I downloaded the single GUI file for mac. I am running OSX high sierra, 10.13.6. 

When I doublclick the pyTC icon, it closes immediately. Not even a window pops up. I am not sure if you are able to help with this issue, is there any other/better information that I can provide?

**Comment by harmsm** [comment]
That sounds really annoying!   Sorry about that, and thanks for the bug report. 

The most helpful thing would be to run the software from a terminal and then send us any output.  

1. Use spotlight to open Terminal.app
2. Type `open /Applications/pytc.app` and hit `Enter` (assuming you copied the program into the /Applications directory). 
3. Copy and paste any output to this thread. 

Hopefully we can get to the bottom of this quickly for you.

**Comment by Dlangela** [comment]
Hi Mike,

Thanks for getting back to me so fast.

Here is the output:

[15:01:14] /Applications :open pytc.app
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/pytc.app.
[15:01:28] /Applications :

I have a hunch that may not be informative…

Any thoughts? Otherwise I could try to install a python framework, but that seems like a pain compared to the .dmg installation.

Thanks,

David


------------------------------------------------------------------------------------

David N. Langelaan, Ph.D.
Assistant Professor
Department of Biochemistry & Molecular Biology
Rm 8-F1, Sir Charles Tupper Medical Building
5850 College St.
Dalhousie University
P.O. Box 15000
Halifax, NS B3H 4R2

On Jul 30, 2018, at 1:55 PM, Mike Harms <notifications@github.com<mailto:notifications@github.com>> wrote:


That sounds really annoying! Sorry about that, and thanks for the bug report.

The most helpful thing would be to run the software from a terminal and then send us any output.

  1.  Use spotlight to open Terminal.app
  2.  Type open /Applications/pytc.app and hit Enter (assuming you copied the program into the /Applications directory).
  3.  Copy and paste any output to this thread.

Hopefully we can get to the bottom of this quickly for you.

**Comment by harmsm** [comment]
Hi David,

We can reproduce the bug here. We'll work on it.   It appears to be mac-specific, maybe even Sierra-specific. Hopefully we can figure out the problem in the next day or so and push a patch.

Unfortunately, until we figure it out, the best you can do is go via a python framework.  If you went that route, you have two options. 

1. Use Jupyter notebooks to fit (as shown here: https://github.com/harmslab/pytc-demos) rather than the GUI. This is what we do in my lab, and is the original design of pytc.  It's got a steeper learning curve than the GUI, but is ultimately way more flexible. For straightforward fits, you should be able to easily adapt the demo notebooks we've already posted. 

2. Try to get the GUI running in a framework.  This could work, but we've found that coaxing pyQT (the graphics back end) to play nice on macs has proven very annoying.  That's probably where this bug came from, actually.  

We'll get right on the fix.  

Mike

**Comment by Dlangela** [comment]
No worries,

Thanks for looking into it. I wish that I could say that this is the first high sierra - specific bug that I have run into…

Cheers,

David
------------------------------------------------------------------------------------

David N. Langelaan, Ph.D.
Assistant Professor
Department of Biochemistry & Molecular Biology
Rm 8-F1, Sir Charles Tupper Medical Building
5850 College St.
Dalhousie University
P.O. Box 15000
Halifax, NS B3H 4R2

On Jul 30, 2018, at 5:16 PM, Mike Harms <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi David,

We can reproduce the bug here. We'll work on it. It appears to be mac-specific, maybe even Sierra-specific. Hopefully we can figure out the problem in the next day or so and push a patch.

Unfortunately, until we figure it out, the best you can do is go via a python framework. If you went that route, you have two options.

  1.  Use Jupyter notebooks to fit (as shown here: https://github.com/harmslab/pytc-demos) rather than the GUI. This is what we do in my lab, and is the original design of pytc. It's got a steeper learning curve than the GUI, but is ultimately way more flexible. For straightforward fits, you should be able to easily adapt the demo notebooks we've already posted.

  2.  Try to get the GUI running in a framework. This could work, but we've found that coaxing pyQT (the graphics back end) to play nice on macs has proven very annoying. That's probably where this bug came from, actually.

We'll get right on the fix.

Mike

**Comment by harmsm** [comment]
Hi David,

We have posted a new mac binary.  It *should* be fixed now.  Sorry about the bug and somewhat slow fix.  Please let us know if this fixed your problem.

Best,

Mike

**Comment by Dlangela** [comment]
Hi Mike,

It seems to be working fine for me. Thanks for taking the time to fix the issue.

Cheers,

David
------------------------------------------------------------------------------------

David N. Langelaan, Ph.D.
Assistant Professor
Department of Biochemistry & Molecular Biology
Rm 8-F1, Sir Charles Tupper Medical Building
5850 College St.
Dalhousie University
P.O. Box 15000
Halifax, NS B3H 4R2

On Aug 25, 2018, at 11:13 AM, Mike Harms <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi David,

We have posted a new mac binary. It should be fixed now. Sorry about the bug and somewhat slow fix. Please let us know if this fixed your problem.

Best,

Mike

**Comment by harmsm** [comment]
Great!  Please let us know if there is anything else we can do to improve pytc.
-Mike
